# command_timeout=1000

# [custom.dotfiles]
# command="bash ./.prompt-dotfiles.sh dotfiles"
# detect_files=[".prompt-dotfiles.sh"]
# description="Status of dotfiles currently installed, and whether they're up to date. Run `dotfiles push/pull/status` for more details."
# style="underline cyan"

# [custom.programs]
# command="bash ./.prompt-dotfiles.sh programs"
# detect_files=[".prompt-dotfiles.sh"]
# description="Indication of whether all the recommended programs are installed. Run `dotfiles-check` for more details."
# style="underline cyan"

# [custom.locals]
# command="bash ./.prompt-dotfiles.sh locals"
# detect_files=[".prompt-dotfiles.sh"]
# description="Indication of whether any local dotfile overrides are loaded. Run `dotfiles-check` for more details."
# style="underline cyan"
